### ISSUE TITLE
Automated code coverage

### ISSUE THREAD

**Issue by skeggse** [hapijs/isemail#1]
I've been using istanbul for code coverage, and dispatching to [coveralls.io](https://coveralls.io) for automated reporting. This requires permissions to access the owner of the repository, and granting that permission is not a decision I can make. @hueniverse what do you think?

**Comment by Marsup** [comment]
It doesn't seem like a huge change to switch from mocha to lab to benefit the other rules we try to follow in the org, it's also able to export to lcov so it's shouldn't be a problem for coveralls.

**Comment by skeggse** [comment]
Thanks for pointing that out, I've been disconnected from the Node world for a while and hadn't heard about lab/code. It doesn't look like lab supports coverage annotations like istanbul, with the comments that let you ignore specific lines/expressions. Is that the case?

**Comment by Marsup** [comment]
It [does](https://github.com/hapijs/lab/blob/8bb11b53368edecb3fe9e183c988aac794df8e6f/lib/coverage.js#L261-L282), it's just not documented.

**Comment by skeggse** [comment]
I was going to go open a documentation issue, but hapijs/lab#329 made me think otherwise, as it's tagged as a `non-issue`...

**Comment by Marsup** [comment]
Do it anyway, I think it was classified non-issue because the thread digressed.

**Comment by skeggse** [comment]
Speaking of digressing, this issue was originally about the use of [coveralls.io](https://coveralls.io) (thanks for the notes about lab and code, though), and whether I have the authority to grant coveralls access to the hapijs organization.

**Comment by skeggse** [comment]
No idea why that commit closed this issue and not #2...

**Comment by skeggse** [comment]
Should this be assigned to me if I'm not the blocker, @hueniverse?

**Comment by hueniverse** [comment]
This project is enabled in travis. I never used coveralls. If you need someone else to do something you should let them know...

**Comment by Marsup** [comment]
The thing is, coveralls is to follow your coverage, all hapi modules (except a few lines that really are uncoverable) are at 100%, so this didn't make sense until now. How far would you be from the 100% if we made changes to hapijs.com to help your tests ?

**Comment by skeggse** [comment]
@hueniverse in this thread I've been asking if I can grant coveralls access to the hapijs project. I'm not comfortable making unilateral decisions for a project I'm new to. Nobody has directly responded to that query.

@Marsup it should be at 100% at the moment, but it can be a nice badge to have. I suppose it's not strictly necessary, it's just a badge I included in the last publication.

**Comment by skeggse** [comment]
Mostly the access boils down to whether I am allowed to hit authorize on the following page:

![Authorization page](http://i.imgur.com/JVGzsXi.png)

**Comment by hueniverse** [comment]
You should bring this up in hapijs/contrib as a new issue. We are using Travis today and adding another service should include everyone first.
