### ISSUE TITLE
why 't@i'  return true

### ISSUE THREAD

**Issue by a4712020502** [hapijs/isemail#154]
var Isemail = require('isemail');
var log = console.log.bind(console, 'result');
var flag = Isemail.validate('t@i',{checkDNS: true},log);

##result true

**Comment by skeggse** [comment]
Are you using the most recent npm version, or the git master?

**Comment by nicolas-goudry** [comment]
Same problem for me through `hapijs` with `toto@toto`…

I checked, `hapi`’s using `2.x.x` and I have `2.2.1` in my `node_modules`.

**Comment by skeggse** [comment]
We've removed `checkDNS`. This is by design now. For the moment, I recommend you pull in an up-to-date list of TLDs, and pass it in as the `tldWhitelist` parameter. You can also set `minDomainAtoms` to `2`.
