### ISSUE TITLE
Module not found: DNS

### ISSUE THREAD

**Issue by qiansen1386** [hapijs/isemail#155]
```
Module not found: Error: Can't resolve 'dns' in '<project path>\node_modules\isemail\lib'
@ ./~/isemail/lib/index.js 5:12-26
```

**Comment by qiansen1386** [comment]
I see, it is not for NodeJS only, is it?

**Comment by Marsup** [comment]
Some features work in browsers but you have to build for it. See #26.

**Comment by michael-reeves** [comment]
According to the thread on that issue on isemail, if the dependency was upgraded to v3 of isemail, this issue would go away, and it'd be a lot simpler to use the package.
