### ISSUE TITLE
Add `allowUnicode` option, default to true

### ISSUE THREAD

**Issue by WesTyler** [hapijs/isemail#156]
We should include an option to "disable" international character recognition, per discussion in https://github.com/hapijs/joi/issues/931 .

Default behavior should be to allow international, since that is the more recent RFC.

**Comment by WesTyler** [comment]
I arbitrarily called it `allowUnicode` just to have enough info for an issue. Defer to @skeggse on implementation details.

**Comment by skeggse** [comment]
I'm working on a rewrite that moves this module closer to being an email address parser with validation as added functionality. As opposed to using a massive state machine, it'll implement the parser as a recursive descent parser. It'll make the code way easier to work with, but in the meantime, I'll try to write a patch that adds this flag.

**Comment by skeggse** [comment]
c640d2e, will land in `v3.1.0`.
