### ISSUE TITLE
How to use this lib without node?

### ISSUE THREAD

**Issue by prashant-saxena** [hapijs/isemail#157]
Hi,
I am using isemail.php on server side. Luckily I have found this counter part for java script but unfortunately this is for Node. I would like to use this lib on my website as I use other java scripts. I haven't seen the code yet and would like to know how to go for conversion? Is it going to be difficult or is it possible?

Cheers
Prashant

**Comment by skeggse** [comment]
`isemail` doesn't have anything particularly unusual - for full compatibility you may need to polyfill some things like `Array#fill`. You'd need to either use a module loader for `punycode` or just embed it.
