### ISSUE TITLE
Maybe transpile?

### ISSUE THREAD

**Issue by cheapsteak** [hapijs/isemail#158]
The es6 used here breaks on old versions of android chrome :(

**Comment by DavidTPate** [comment]
`isemail` doesn't really have anything unusual within it, you'll likely need to polyfill some of the features and use a bundler anyways for things like `punycode`, releasing a transpiled version is not something that I expect us to do as Hapi will shortly be targeting Node 8 (and have LTS support for Node 6).

You'll want to take a look at some other issues for some hints on what you need like #26 #27 and I'm sure a few others but those should help you with what others have done to hack it to get it working in the browser.

We don't explicitly support browsers with this module so I'm going to close this issue.

**Comment by dashed** [comment]
I had a need for this library with a project using `create-react-app` and [`react-app-rewired`](https://github.com/timarney/react-app-rewired).

So I created this lib to resolve this es6+ issue: https://github.com/dashed/react-app-rewire-babel-loader

For lurkers, this is how I used it within a CRA project:

```js
// config-overrides.js
// see: https://github.com/timarney/react-app-rewired

const path = require("path");
const fs = require("fs");

const rewireBabelLoader = require("react-app-rewire-babel-loader");

// helpers

const appDirectory = fs.realpathSync(process.cwd());
const resolveApp = relativePath => path.resolve(appDirectory, relativePath);

module.exports = function override(config, env) {

  // white-list some npm modules to the babel-loader pipeline
  // see: https://webpack.js.org/configuration/module/#rule-include

  config = rewireBabelLoader.include(
    config,
    resolveApp("node_modules/isemail")
  );

  return config;

};
```

**Comment by thallada** [comment]
I don't think this is a non-issue. I have a fairly large project with 1000+ dependencies that needs to run in IE11. Out of all of those dependencies, isemail is the only package with ES6 syntax. I have to manually specify in my webpack config to transpile only this package in my node_modules folder. Isn't it standard practice for npm packages to transpile to ES5 before publishing to NPM?

**Comment by skeggse** [comment]
>Isn't it standard practice for npm packages to transpile to ES5 before publishing to npm?

Not entirely. The hapijs organization hosts modules that are designed for server-side use, and we as an organization decided to relatively quickly drop support for older versions of Node.js. We use the latest features to ease development, and browser support is not within scope.

**Comment by Marsup** [comment]
You're right that it is standard practice, but just because it is standard doesn't mean it's the right thing to do. As an organization we took a vote a while ago and decided not to do it, imho there are strong arguments against doing it that still stand even today as the situation hasn't evolved.
