### ISSUE TITLE
Email validation issue

### ISSUE THREAD

**Issue by veera83372** [hapijs/isemail#161]
```js
$ node
> var Isemail = require('isemail');

> Isemail.validate('test@iana.org');
true
> Isemail.validate('test@iana');
true
```
#### Which result you had ?
true

#### What did you expect ?
false

**Comment by skeggse** [comment]
This is the correct behavior. We test the email address for syntax, not deliverability. If your concern is specifically with single-atom domains, use the `minDomainAtoms` parameter, but know that there are email addresses in the wild at top-level domains, such as `@io`.

**Comment by veera83372** [comment]
I hope, adding  ```isTldMail``` to the Email options might make sense. It gives the flexibility to customize.

**Comment by skeggse** [comment]
If what you're asking for is the ability to only allow a specific set of top-level domains, then use the `tldWhitelist` option.
