### ISSUE TITLE
Some code is not supported by advertised node v4

### ISSUE THREAD

**Issue by ZacharyRSmith** [hapijs/isemail#166]
[isemail says it runs on node >=4.0.0](https://github.com/hapijs/isemail/blob/master/package.json#L19), but [it has arrow functions](https://github.com/hapijs/isemail/blob/master/lib/index.js#L174), which [are not supported in node v4.0](http://node.green/#ES2015-functions-arrow-functions)

**Comment by kanongil** [comment]
Your assertion is wrong. Do you haven an actual issue?

**Comment by Marsup** [comment]
I second that, we'd know by now if it was incompatible :)

**Comment by ZacharyRSmith** [comment]
My bad, I somehow misread the chart.  Thanks for looking.
