### ISSUE TITLE
react-native issue

### ISSUE THREAD

**Issue by vasilich6107** [hapijs/isemail#169]
Hi, thanks for the library. But I failed to use it in react native project due to the error
`TypeError: Cannot read property '1' of undefined` in `internals.normalize` function

**Comment by scottwarren** [comment]
Can you please provide a [minimal working example](https://stackoverflow.com/help/mcve) of the problem?

**Comment by skeggse** [comment]
We do not officially support environments other than Node.js, which is causing this issue - we rely on `process.version` internally to determine whether we need to work around a V8 `String#normalize` issue. I suspect we can do this with feature detection instead, so I'll look into that as a possible modification that would happen to fix the issue you're seeing.

**Comment by wswoodruff** [comment]
@vasilich6107 This line is actually checking the major version of Node being run! https://github.com/hapijs/isemail/blob/7df43da472898a944c03deeff853512ee2a01894/lib/index.js#L1342

In a node context, (in my REPL) if I run process.version I get
`v9.3.0` -- so the [1]th index of that is `9`.

Looks like react-native also has `process` available but not `version` -- perhaps you could set `.version` on process in your code, not sure how you feel about that

**Comment by skeggse** [comment]
Fixed in 143a684 @v3.1.2.
