### ISSUE TITLE
TLD check on .png

### ISSUE THREAD

**Issue by VeeeneX** [hapijs/isemail#170]
isemail marked `apple-touch-icon-60x60@2x.png` as valid email with valid TLD. But its not listed in [ICANN](https://www.icann.org/resources/pages/tlds-2012-02-25-en) nor in [IANA](https://www.iana.org/domains/root/db), so expected behaviour is to report `errUnknownTLD`

```js
const tldExpectations = [
    ['apple-touch-icon-60x60@2x.png', diag.errUnknownTLD],
    ['shouldbe@invalid', diag.errUnknownTLD],
    ['shouldbe@example.com', diag.valid]
];
```
I've tried adding it to tldExpectations to see wheter it report `errUnknownTLD` but without luck. According to option `tldWhitelist` I should set my tldWhitelist on my own?

Works well with [tlds](https://www.npmjs.com/package/tlds) and with the definition of `tldWhitelist`, but there is a problem with case sensitivity. TLD is case insensitive according to  https://stackoverflow.com/questions/9807909/are-email-addresses-case-sensitive so I suggest simply check `tldWhitelist` with case insensitivity.
So the actual question is whether this should be added as a dependency to check TLD against this list.

This may be an answer:
```js
if (Array.isArray(options.tldWhitelist)) {
        return internals.indexOf.call(options.tldWhitelist, tldAtom.toLowerCase()) !== -1;
}
return internals.hasOwn.call(options.tldWhitelist, tldAtom.toLowerCase());
```

For those who want to use it right away:

```packpage.json
    "isemail": "hapijs/isemail#refs/pull/171/head",
```

**Comment by WesTyler** [comment]
> its not listed in ICANN nor in IANA, so expected behaviour is to report errUnknownTLD

isemail does not check for deliverability of emails (and therefore TLDs), only that they are compliant with the RFCs that govern the rules of email.

As inconvenient as it is, per RFCs, I believe `apple-touch-icon-60x60@2x.png` truly is a valid email address. :\

Closing, as this is not really an issue with isemail.

**Comment by skeggse** [comment]
Hey @WesTyler, this is actually an issue - isemail isn't performing the whitelist check in a case-insensitive way.
