### ISSUE TITLE
can not validate test@test

### ISSUE THREAD

**Issue by gusyang** [hapijs/isemail#179]
isemail.validate("**test@test**") === true
should have correct domain like **".c"** one" ." and 1 charactor at least.

**Comment by skeggse** [comment]
That is a valid email address. Use `minDomainAtoms` if you want to break spec.

**Comment by WesTyler** [comment]
Dangit @skeggse you ninja'd me. I was about to click "Close and comment" when my page flipped the issue to closed already haha

**Comment by gusyang** [comment]
thank you!
