### ISSUE TITLE
Underscore not allowed in domain name, why?

### ISSUE THREAD

**Issue by deejbee** [hapijs/isemail#181]
It should allow this.  Some email addresses are being rejected.

**Comment by WesTyler** [comment]
```js
isemail.validate('email_test@email.com')
// true
```

**Comment by WesTyler** [comment]
Feel free to reopen with more details.

**Comment by WesTyler** [comment]
I misread the title, and there were no code examples or details in the issue so I closed prematurely.

Looking at RFCs

**Comment by WesTyler** [comment]
Hm, may need to defer to @skeggse here. 

I'm seeing in [RFC 2181](https://tools.ietf.org/html/rfc2181#section-11) and it appears that there is only a length-limit on domains:
>any binary string whatever can be used as the label of any
   resource record.  Similarly, any binary string can serve as the value
   of any record that includes a domain name as some or all of its value

But I am also seeing conflicting information from various people regarding [RFC 1123 Sec 2.1](http://www.ietf.org/rfc/rfc1123.txt) which specifies that hostnames follow the LDH (letter, digit, hyphen) rule.

**Comment by skeggse** [comment]
This is operating as expected. I should've more careful about terminology, but what you're describing is a syntax error. Domain names in the domain name system have few restrictions. Host names as used in internet protocols are limited to LDH.

RFC 5321 _explicitly_ requires, per section 4.1.2, that SMTP servers which receive a command with invalid character codes (RFC 5321 in the same section gives the underscore as an example) MUST reject the command with a 501 response.
