### ISSUE TITLE
isemail.validate throws on non-string argument

### ISSUE THREAD

**Issue by ungoldman** [hapijs/isemail#184]
If a value passed to `isemail.validate` happens to not be a string, the function throws a TypeError.

```
> var isemail = require('isemail')
undefined
> isemail.validate()
TypeError: Cannot read property 'normalize' of undefined
    at Object.internals.normalize (.../node_modules/isemail/lib/index.js:190:18)
    at Object.exports.validate.internals.validate (.../node_modules/isemail/lib/index.js:322:23)
> isemail.validate(1)
TypeError: email.normalize is not a function
    at Object.internals.normalize (.../node_modules/isemail/lib/index.js:190:18)
    at Object.exports.validate.internals.validate (.../node_modules/isemail/lib/index.js:322:23)
```

I think it might be worth just returning false here. Anything that doesn't have the normalize method is not a string and therefore not a valid email.

**Comment by skeggse** [comment]
That's a reasonable proposal. I think I'm not in favor, though:

You're expected to pass in a string, and as a dev I would expect some exceptional behavior if I violate that precondition. If I were to do something dumb like use a subclass of `String` for some of my string values, and one of them got passed in to `isemail`, I'd want it to yell at me, because otherwise it might be rejecting what should be valid emails.

I do think it's worth making this check explicit, instead of having a random `TypeError` from somewhere inside the module.

Why do you desire this behavior? How is it beneficial?

**Comment by ungoldman** [comment]
> Why do you desire this behavior? How is it beneficial?

It would make it simpler to pass in an unspecified value from user input and verify that it's a valid email address. Knowing it's a valid email, I can infer it's also a valid string.

If it's important to only return true or false if the parameter is a string, I'm in favor of throwing an exception with a more informative error. Something along the lines of:

```
Error: parameter "email" must be of type string, was "undefined"
```

...with a corresponding stack trace that allows the user to infer the problem more directly.

For the purpose of the thing I'm working on today, It didn't matter if the input was a valid string or not, just a valid email (and therefore also a valid string), so it would be simpler for me to have a guaranteed true or false return value from this function rather than having to do my own type checking before passing it in (i.e. less typing).

So! Up to you how you think it would be best to handle this given the conventions of this module and how it's typically used in the wild.

**Comment by ungoldman** [comment]
Example of what I'm writing today:

```js
function validateEmail (email) {
  if (typeof email !== 'string') return false
  // NOTE: throws if not a string
  // https://github.com/hapijs/isemail/issues/184
  return isemail.validate(email)
}
```

How can I help resolve this issue? Happy to open a PR with a type check in `isemail.validate` and an error specific to the function (or returning false 😄).

**Comment by WesTyler** [comment]
> Happy to open a PR with a type check in isemail.validate and an error specific to the function 

That would be great! I'm with @skeggse in preferring a thrown error over returning `false`.

**Comment by ungoldman** [comment]
LGTM! Thanks @skeggse 👍
