### ISSUE TITLE
Validation fails on long email addresses

### ISSUE THREAD

**Issue by ankurkaushal360** [hapijs/isemail#190]
For an email address like this, `aaaaahewoihewioewhioewhjewiorhewiorhewiorhewiorhewrewhroewhroewhewiohrewiorhewoirhe@a.com`, the validation fails when it should pass the validation test.

**Comment by skeggse** [comment]
Per [RFC 5321](http://tools.ietf.org/html/rfc5321#section-4.5.3.1.1), that is not a valid email address.
