### ISSUE TITLE
Use of 'util' not browser / react native friendly

### ISSUE THREAD

**Issue by luislobo** [hapijs/isemail#196]
I don't know which would be the best implementation here but, some work could be added in `lib/utils.js` to make it browser / react native compatible, by not using `util` when on a browser like environment.

**Comment by skeggse** [comment]
We don't support execution environments that aren't a recent version of Node. You can use a bundler and browser shims to package this module up for consumption in other environments.

**Comment by alexander-schranz** [comment]
I lately upgraded form webpack 4 to 5 and did run into issue with `util` library. If I understand correctly I need to require `util` package myself now?

Will link the reference stackoverflow question here: https://stackoverflow.com/questions/64402821/module-not-found-error-cant-resolve-util-in-webpack Maybe it helps others running into the same issue.

**Comment by PoojaDaredi** [comment]
I ran into same issue and resolved by:-

1) delete package-lock.json file
2) npm install

Everything should work now, it was the package-lock.json that blocked npm to download old versions of dependencies.
