### ISSUE TITLE
Not working in Android Webview and IE11

### ISSUE THREAD

**Issue by PhilippSchreiber** [hapijs/isemail#199]
Because of the use of `String.prototype.normalize()` the usage of isemail stops the web site from working in Android Webview and IE11.

Details: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize

**Comment by PhilippSchreiber** [comment]
Hm perhaps I do something wrong but normally I just do `yarn add isemail` and start using the package via `import {x} from 'y'`.

**Comment by WesTyler** [comment]
If you're developing for browsers, and specifically needing to support IE, you'll want to use something like Babel to transpile your code for web. There are tangential benefits like tree shaking and code splitting and all that, but ultimately it will solve for this issue where you used a package developed for Node.js inside of the browser instead.

**Comment by smeijer** [comment]
I've finally found it! IE devtools wasn't showing any error, but this package broke my app for that browser anyway. The page stayed just blank.

Yes, we build with babel. But node_modules aren't transpiled. Saying that it's our responsibility to transpile to platforms we are targetting, is a little easy to say. It often doesn't work like that.

If supporting IE is out of the scope of this package; then that's fine. But I guess the readme could mention this. I didn't expect something as simple as email validation, could have limited browser support.

That being said. We definitely should take responsibility. I just noticed that this package also depends on `punycode` and `util`. Making it more clear that this util is not meant to be used in the browser at all. It's more meant as server side (node) library.

Which again is fine. But a fair warning in the readme would be much appreciated.

**Comment by zikuai** [comment]
> Because of the use of `String.prototype.normalize()` the usage of isemail stops the web site from working in Android Webview and IE11.
> 
> Details: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize

I have the same problem with you
