### ISSUE TITLE
Support for 0.8.x

### ISSUE THREAD

**Issue by skeggse** [hapijs/isemail#2]
The tests currently [fail](https://travis-ci.org/hapijs/isemail/jobs/80059171) for Node 0.8.x. Should we drop support or try to make chai happy?

**Comment by Marsup** [comment]
Node 0.8 is way past support time, I vote for deprecation.

**Comment by skeggse** [comment]
Ha haven't actually pushed this yet.

**Comment by skeggse** [comment]
No idea why that commit closed this issue and not #1...
