### ISSUE TITLE
DNS MX resolution error handling is broken

### ISSUE THREAD

**Issue by bf** [hapijs/isemail#21]
The handling of errors after DNS resolution of invalid domains always returns `true` even though both the domain and the MX record for the domain does not exist.

**Comment by sfgdgdbdbdfbsdfbsdf** [comment]
ARE YOU JUST AN ASSHOLE OR ARE YOU FUCKING RETARDED YOU DUMB FUCK???!!! WHAT FUCKING "CASE" ARE YOU FUCKING TALKING ABOUT YOU DIRTY NIGGER PIECE OF SHIT???

YOU FUCKING DIRTY NIGGER PIECE OF FUCKING SHIT, EAT SHIT AND DIE YOU FUCKING CUNT BITCH ASSHOLE MOTHER FUCKER!!! FUCK YOU BITCH!!! I WILL NOW DDOS YOUR FUCKING WEBSITE YOU FUCKING NIGGER!!!!!!!!!!

**Comment by dare-devil-arrives** [comment]
Is this fix included in the stable release?

**Comment by Marsup** [comment]
This would need to at least pass the tests.

**Comment by skeggse** [comment]
The `checkDNS` option has been removed in `3.0.0`.
