### ISSUE TITLE
International email support

### ISSUE THREAD

**Issue by antony** [hapijs/isemail#23]
I've raised a "bug" against joi's email validator, and it has been suggested by @Marsup that I reference / summarise it here also, since Joi depends on isemail for validation.

The [original issue can be found here](https://github.com/hapijs/joi/issues/931)

We have a number of Danish users who have danish characters in their email addresses. From the research I've done it appears that these are actually invalid email addresses, however there is growing support for international characters across a number of major email providers and smtp/pop3 implementations.

Fundamentally, we'd need to support the email jØrgen@somedomain.com as it is compliant with https://tools.ietf.org/html/rfc6530 - it is usable on a number of major providers, and registerable as a new email address on another set of providers.

It seems like the existence of these email addresses means that it would be wise to support them, via use of an optional configuration parameter.

As with my example in the linked github issue, using google as an example, would turn this parameter ON for send/receive, and OFF for signups.

My proposal is a configuration parameter something like `international: true/false`, or `compliance: rfc5322/rfc6530`, or perhaps even `rfc:6530`

Note that it does seem that the new RFC rfc6530 is an evolving standard since 2012, but the real-world use of this type of email, and the issues I'm having today make me think that there should be some sort of support for it, as an option.

**Comment by skeggse** [comment]
Thank you. How is this issue different from #17?

**Comment by antony** [comment]
Ah, it isn't. That one had totally slipped my notice. I'll close this in favour of #17
