### ISSUE TITLE
Please add ES5 compatibility

### ISSUE THREAD

**Issue by maxharris9** [hapijs/isemail#27]
In order to use this module in an ES5 environment (Safari 9), I had to add a little snippet to `node_modules/isemail/package.json`:

```
  "browserify": {
    "transform": [["babelify", { "presets": ["es2015"] }]]
  }
```

Please consider adding this to your package.json. (Also, thanks for maintaining this module!)

**Comment by arb** [comment]
It is up to the developer to make the code work in their environment. Across the org, we do not include a single line of cleint-side transformation code.

Please see...
https://github.com/hapijs/joi/issues/528
https://github.com/hapijs/boom/pull/58

And many other issues in the organization related to this.
