### ISSUE TITLE
Broken in react-native

### ISSUE THREAD

**Issue by dsernst** [hapijs/isemail#29]
When I try to import this package in a `react-native` project, I get this fatal error:

```
Unable to resolve module dns from .../node_modules/isemail/lib/index.js
```

Here's the line that refers to: https://github.com/hapijs/isemail/blob/master/lib/index.js#L5

**Comment by Marsup** [comment]
This module is used for some features of this library, so depending on your build system either you ignore the module or figure out a way to replace it with something that works for you.

**Comment by mzedeler** [comment]
Is it possible that a browser version of the library without the dns dependency could be provided?

**Comment by sfgdgdbdbdfbsdfbsdf** [comment]
ARE YOU JUST AN ASSHOLE OR ARE YOU FUCKING RETARDED YOU DUMB FUCK???!!! WHAT FUCKING "CASE" ARE YOU FUCKING TALKING ABOUT YOU DIRTY NIGGER PIECE OF SHIT???

YOU FUCKING DIRTY NIGGER PIECE OF FUCKING SHIT, EAT SHIT AND DIE YOU FUCKING CUNT BITCH ASSHOLE MOTHER FUCKER!!! FUCK YOU BITCH!!! I WILL NOW DDOS YOUR FUCKING WEBSITE YOU FUCKING NIGGER!!!!!!!!!!

**Comment by tstirrat15** [comment]
Why isn't it listed as a peer dependency on NPM?

Also, it'd be nice to have a way to make this optional.

**Comment by arb** [comment]
@mzedeler regarding browser version please see:
https://github.com/hapijs/isemail/issues/26
https://github.com/hapijs/joi/issues/528
https://github.com/hapijs/boom/pull/58
as well as many other "browser version" related issues in the hapijs org

@tstirrat15 because it's not a peer dependency. `dns` is a core module in Node.

**Comment by tstirrat15** [comment]
Ah, that makes sense. I was running into browser issues. I found another way around it, though. Thanks!

**Comment by skeggse** [comment]
`dns` is no longer used in `isemail`. As of `3.0.0`, there's a new `punycode` dependency - not sure what y'all will need to do to get that working.
