### ISSUE TITLE
Where is the documentation? I saw a readme file but no INSTRUCTIONS in there

### ISSUE THREAD

**Issue by asdgdfhgfsdg** [hapijs/isemail#33]
Please send the link to full INSTRUCTIONS on exact usage so non-javascript-programmers can do it and so you don't need a computer science degree to use this.

**Comment by asdgdfhgfsdg** [comment]
I need working html or php example that I can copy and paste into my code.

**Comment by Marsup** [comment]
Dude, stop, you're just aggravating your case.
