### ISSUE TITLE
Explore ANY DNS Query

### ISSUE THREAD

**Issue by skeggse** [hapijs/isemail#5]
The `checkDNS` option asks the isEmail module to run a number of DNS queries to determine whether the domain exists, and whether the domain actually has an **MX** record. Does it make sense to combine the four queries into one wildcard query, or would that make it take longer/need to buffer more data?

Regardless, pending nodejs/node#2848.

**Comment by sfgdgdbdbdfbsdfbsdf** [comment]
ARE YOU JUST AN ASSHOLE OR ARE YOU FUCKING RETARDED YOU DUMB FUCK???!!! WHAT FUCKING "CASE" ARE YOU FUCKING TALKING ABOUT YOU DIRTY NIGGER PIECE OF SHIT???

YOU FUCKING DIRTY NIGGER PIECE OF FUCKING SHIT, EAT SHIT AND DIE YOU FUCKING CUNT BITCH ASSHOLE MOTHER FUCKER!!! FUCK YOU BITCH!!! I WILL NOW DDOS YOUR FUCKING WEBSITE YOU FUCKING NIGGER!!!!!!!!!!

**Comment by skeggse** [comment]
No longer applicable.
