### ISSUE TITLE
Explore using hapijs.com to host DNS records for testing

### ISSUE THREAD

**Issue by skeggse** [hapijs/isemail#7]

**Comment by sfgdgdbdbdfbsdfbsdf** [comment]
ARE YOU JUST AN ASSHOLE OR ARE YOU FUCKING RETARDED YOU DUMB FUCK???!!! WHAT FUCKING "CASE" ARE YOU FUCKING TALKING ABOUT YOU DIRTY NIGGER PIECE OF SHIT???

YOU FUCKING DIRTY NIGGER PIECE OF FUCKING SHIT, EAT SHIT AND DIE YOU FUCKING CUNT BITCH ASSHOLE MOTHER FUCKER!!! FUCK YOU BITCH!!! I WILL NOW DDOS YOUR FUCKING WEBSITE YOU FUCKING NIGGER!!!!!!!!!!

**Comment by skeggse** [comment]
No longer applicable.
