### ISSUE TITLE
Using milestones

### ISSUE THREAD

**Issue by AdriVanHoudt** [hapijs/isemail#8]
I can see this module is using releases and tags but it would be nice to group closed PR/issues with milestones for easiness, also this will allow http://hapijs.com/updates to show the issues/PR's that led to the release.

**Comment by skeggse** [comment]
This project is pretty slow moving in that there's not a whole lot of things to change. I'll try to keep this in mind whenever I update, but it won't be often.

**Comment by AdriVanHoudt** [comment]
Yeah was more of a suggestion, you can still retroactive make a milestone and assing issues and PR's to it and close I think though
